# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

matrix:
  include:
    - os: osx
      r: release
    - os: linux
      r: release
      env:
      - BUILD_PKGDOWN=true

# DO NOT CHANGE THE CODE BELOW
before_install:
 - R -q -e 'install.packages(c("remotes", "curl"))'
 - R -q -e 'remotes::install_github("ropenscilabs/tic")'
 - R -q -e 'tic::prepare_all_stages()'
 - R -q -e 'tic::before_install()'

 - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install p7zip; fi

install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: false
dist: xenial
cache: packages
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libudunits2-dev
      - libgeos-dev
      - libgdal-dev
      - p7zip-full
      - pandoc

#env
env:
  global:
  - MAKEFLAGS="-j 2"

#services
services:
